<template>
    <div class="row about">
        <h2 class="text-center"><strong>How it works</strong></h2>
        <div class="grid-container">
            <div class="grid-child grid-child-1">
                <div class="grid-child-title">
                     SARS-CoV-2 proximal interactome enhanced enrichment 
                </div>
                <div class="grid-child-content">
                    The protein-protein interaction pre-print puts forward a rich dataset of 28 viral proteins each in 
                    independent interaction with host proteins in a 10 nm radius inside the living cell (HEK293). 
                    This proximal interactome pioneer research aims at pin point essential host proteins for the viral 
                    cycle to happen in the cellular context. The resulting network of interaction, including all of the 
                    interactors, depicts a continuous specter of protein roles and biological functionality rendering the 
                    apprehension of key processes impossible. This page is a visualization of the enhanced enrichment of 
                    the SARS-CoV-2 proximal interactome dataset which highlights discrete and relevant biological 
                    functionality and its set of genes.
                </div>
            </div>
            <div class="grid-child grid-child-2">
                <div class="grid-child-title">
                    Gene Ontology Enrichment
                </div>
                <div class="grid-child-content">
                    Gene Ontology is an informative resource and a collaborative effort for classifying sets of genes by 
                    their attributes. Here the focus is mainly on biological processes (BP) and cellular components (CC) 
                    annotations available for the sets of interactors provided. Each interactor is annotated to its GO 
                    terms with respect to the GO annotations provided by Uniprot. Then, GO terms are scored using the 
                    Fisher-Weight algorithm using topGO package. 20 most significant terms (unique and redundant) along 
                    with their interactors are retrieved. The interactive graph depicts the Gene Ontology most relevant 
                    terms in its hierarchical layout context.
                </div>
            </div>
            <div class="grid-child grid-child-3">
                <div class="grid-child-title">
                    Protein Complex Enrichment
                </div>
                <div class="grid-child-content">
                    CORUM provides manually curated protein complexes from scientific reviews. It offers an additional 
                    layer of information on top of the Gene Ontology enrichment. A list of the most relevant protein 
                    complexes is generated by querying interactors against a locally downloaded snapshot of the database 
                    for matches in protein complex components. Several occurrences highlight an interplay between the bait 
                    and the protein complex.
                </div>
            </div>
        </div>
    </div>
</template>
<script>
export default {
    
}
</script>
<style scoped>
.grid-container {
    display: grid;
    padding-top: -0.5em;
    grid-template-rows: 300px;
    grid-template-columns: repeat(3, 1fr);
    column-gap: 1em;
}
.grid-child {
    background-color: #CFD5E8;
    /* border-radius: 25px; */
}
.grid-child-title {
    padding-top: 1em;
    padding-left: 1em;
    font-weight: 900;
    font-size: 20px;
    /* text-align: center; */
}
.grid-child-content {
    font-size: 16px;
    padding: 1em;
    text-align: justify;
}
.about {
    margin-right: 1em;
    margin-left: 1em;
}

/* .grid-child-1 {
    background-color:#f2fc90;
}

.grid-child-2 {
    background-color: #6da378;
}

.grid-child-3 {
    background-color: #eb8f7a;
} */
</style>